title: PeopleDAO
description: "@TODO"
url: "@TODO"
repository: "@TODO"

version: "@TODO" # Generate random string when updating meta assets
ogImageWidth: 1000
ogImageHeight: 1000
msAppColor: "@TODO"
appleAppColor: "@TODO"
themeColor: "@TODO"