title: PeopleDAO
description: "A meta DAO for Web3 to unite $PEOPLE across the globe and deliver positive impact"
url: "https://people-dao.com"
repository: "https://github.com/People-DAO/website"

version: "p8ty9jj7vml3gcd8" # Generate random string when updating meta assets
ogImageWidth: 420
ogImageHeight: 630
msAppColor: "#d069d7"
appleAppColor: "#d069d7"
themeColor: "#ffffff"