title: PeopleDAO
description: "PeopleDAO"
url: "https://people-dao.com"
repository: "https://github.com/People-DAO/website"

version: "1.0" # Generate random string when updating meta assets
ogImageWidth: 1000
ogImageHeight: 1000
msAppColor: "@TODO"
appleAppColor: "@TODO"
themeColor: "@TODO"